#----------------------------------------------------
#Name: Efrain Magallon & Pingchuan Li
#Class accounts: masc1984 & masc2020
#Class: CS 570, Summer 2016
#Assignment: Assignment 1 - semaphore
#File: Makefile
#----------------------------------------------------

EXEC = bots

$(EXEC):
	    gcc -o bots a1.c  -lrt -lpthread
	    rm -f *.o
	    ./bots
	
clean:
	 rm -f *.o core a.out $(EXEC)
	
	

       
	
	
